Repository MiiingGaeng/news-feed-site, pull requests merged in 2025-02, with the labels that each got.

#5 feat: 레이아웃 구성 요소 추가 및 라우터 구조 개선
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/shared/Router.jsx
Labels: 🐥 수민

#9 style: Footer 및 Header 주석 추가 및 레이아웃 개선 #7
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
Labels: 🐥 수민

#10 feat: Detail 전체 UI 레이아웃 작업 / Button, CloseButton 컴포넌트 추가 및 페이지 이동 기능 구현 #1
  index.html
  src/common/Button.jsx
  src/components/feed/CloseButton.jsx
  src/layout/Footer.jsx
  src/layout/Layout.jsx
  src/pages/Detail.jsx
  src/shared/Router.jsx
  src/styles/styledComponents.js
Labels: ✨ feat, 📦add, 🎨 style, 🐻 민경

#12 feat: FeedList, FeedCard UI 만들기/ Like 버튼 생성 / 카드 Link 기능 구현 / 카드 내부 요소 styled-components 적용 #4
  eslint.config.js
  src/components/feed/CloseButton.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedList.jsx
  src/components/feed/Like.jsx
  src/constants/MOCK_DATA.js
  src/contexts/FeedContext.jsx
  src/layout/Layout.jsx
  src/pages/Feed.jsx
  src/supabase/client.js
Labels: ✨ feat, 😺영진

#23 feat: Feed 모달창에 FeedForm 컴포넌트 추가 및 스타일 수정 #11
  src/App.jsx
  src/api/fetchData.js
  src/components/common/Modal.jsx
  src/components/feed/CloseButton.jsx
  src/components/feed/FeedForm.jsx
  src/contexts/FeedContext.jsx
  src/main.jsx
  src/pages/Detail.jsx
  src/pages/Feed.jsx
  src/shared/Router.jsx
Labels: ✨ feat, 📦add, 🐥 수민

#27 feat: FeedForm 컴포넌트에 데이터 추가 및 업데이트 기능 구현 #26
  src/api/insertOrUpdateData.js
  src/components/feed/FeedForm.jsx
  src/pages/Feed.jsx
Labels: ✨ feat, 🐥 수민

#25 feat: supabase 데이터 패치 및 Detail/FeedEdit 페이지 구현 #16
  src/api/fetchData.js
  src/components/feed/Comments.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedForm.jsx
  src/components/feed/FeedList.jsx
  src/pages/Detail.jsx
  src/pages/Feed.jsx
  src/pages/FeedEdit.jsx
  src/pages/Login.jsx
  src/shared/Router.jsx
  src/styles/globalStyle.css
  src/styles/styledComponents.js
  yarn.lock
Labels: ✨ feat, 🎨 style, 🐻 민경

#30 feat: 댓글 추가/삭제 로직 구현 #28
  src/api/deleteData.js
  src/api/insertOrUpdateData.js
  src/components/feed/Comments.jsx
Labels: ✨ feat, 🐻 민경

#33 feat: MainButton 컴포넌트 스타일링 및 Home 페이지에 통합 #29
  src/components/common/NavigationButton.jsx
  src/pages/Home.jsx
  src/styles/globalStyle.css
Labels: ✨ feat, 📦add, 🎨 style, 🐥 수민

#34 feat: MyPage 기본 UI 및 Input 컴포넌트 생성 #6
  package-lock.json
  src/assets/image/profile_default.png
  src/common/Input.jsx
  src/pages/Mypage.jsx
  yarn.lock
Labels: 📦add, 🎨 style, 🐈‍⬛애리

#36 feat: 회원가입, 로그인, AuthContext 구현 완료 #13, #24
  src/App.jsx
  src/contexts/AuthContext.jsx
  src/layout/Layout.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  src/styles/globalStyle.css
Labels: ✨ feat, 🦋 미경, 🪫 도현

#37 feat: react-hook-form을 사용하여 피드 추가 폼 유효성 검사 구현 및 금칙어 필터링 추가
  package.json
  src/components/feed/FeedForm.jsx
  yarn.lock
Labels: ✨ feat, 🔨 refactor, 🐥 수민

#38 style: 홈 페이지에 게시물 보기 버튼 추가 및 버튼 레이아웃 개선
  src/pages/Home.jsx
Labels: 🎨 style, 🐥 수민

#40 feat: 게시글/댓글 수정 로직 구현
  .github/PR_TEMPLATE.md
  package-lock.json
  package.json
  src/api/fetchData.js
  src/api/insertOrUpdateData.js
  src/components/feed/Comments.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedForm.jsx
  src/components/feed/FeedList.jsx
  src/contexts/AuthContext.jsx
  src/pages/Detail.jsx
  src/pages/FeedEdit.jsx
  yarn.lock
Labels: 📃 docs, ✨ feat, 🧹chore, 🐻 민경

#42 feat: 모달 컴포넌트 재구성 및 추가, 피드 페이지에 스티키 메뉴 추가
  src/components/feed/FeedAddButton.jsx
  src/components/feed/FeedList.jsx
  src/components/feed/Modal.jsx
  src/layout/Layout.jsx
  src/layout/StickyMenu.jsx
  src/pages/Feed.jsx
Labels: ✨ feat, 🎨 style, 🐥 수민

#43 feat: AuthContext에 userId 받아오는 코드 추가
  package.json
  src/contexts/AuthContext.jsx
  yarn.lock
Labels: ✨ feat, 🦋 미경, 🪫 도현

#44 feat: feed추가시 로그인한 유저의 아이디를 writer_id에 추가 #26
  src/components/feed/FeedForm.jsx
  src/contexts/AuthContext.jsx
Labels: ✨ feat, 🐥 수민

#45 style: 스티키 메뉴 위치 수정 및 패딩 조정
  src/layout/StickyMenu.jsx
Labels: 🎨 style, 🐥 수민

#51 feat: feed 추가시 자동 갱신 로직 추가
  src/components/feed/FeedForm.jsx
  src/pages/Feed.jsx
Labels: ✨ feat, 🐥 수민

#52 [Feat] supabase에서 유저정보 가져오기 #49
  src/pages/Mypage.jsx
Labels: ✨ feat, 🐈‍⬛애리

#53 feat: Detail / Comments 컴포넌트에서 로그인 여부 로직 추가
  src/components/feed/Comments.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedForm.jsx
  src/pages/Detail.jsx
  src/pages/FeedEdit.jsx
  src/pages/Mypage.jsx
Labels: ✨ feat, 🧹chore, 🐻 민경

#58 feat: header 로그아웃 기능 구현
  src/contexts/AuthContext.jsx
  src/layout/Header.jsx
Labels: ✨ feat, 🐥 수민

#60 feat: 로그인 상태에 따라 마이페이지 및 피드 추가 버튼 접근 제어
  src/layout/StickyMenu.jsx
Labels: ✨ feat, 🐥 수민

#63 refactor: FeedForm 컴포넌트 분리 / feat: 댓글 금칙어 필터링
  src/components/feed/AddFeedForm.jsx
  src/components/feed/Comments.jsx
  src/components/feed/EditFeedForm.jsx
  src/components/feed/FeedForm.jsx
  src/pages/Feed.jsx
  src/pages/FeedEdit.jsx
  src/styles/styledComponents.js
Labels: ✨ feat, 🔨 refactor, 🐻 민경

#64 [FEAT] 좋아요 버튼 구현
  src/api/fetchData.js
  src/components/feed/FeedCard.jsx
  src/components/feed/Like.jsx
  src/pages/Feed.jsx
  yarn.lock
Labels: ✨ feat, 😺영진

#66 [Feat] 유저정보 update기능, 해당 유저의 피드 모아보기 기능 및 input 컴포넌트와 mypageUI 다듬기#48 #49
  package.json
  src/common/Input.jsx
  src/pages/Mypage.jsx
  yarn.lock
Labels: ✨ feat, 🎨 style, 🐈‍⬛애리

#74 refactor: Swal 라이브러리를 사용한 UX 개선
  README.md
  src/components/common/Alert.js
  src/components/feed/AddFeedForm.jsx
  src/components/feed/Comments.jsx
  src/components/feed/EditFeedForm.jsx
  src/components/feed/FeedCard.jsx
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
  vite.config.js
Labels: 🔨 refactor, 🐻 민경

#76 feat: 로그인, 회원가입 유효성검사 및 예외처리 추가, 유저 안내 추가
  src/assets/image/user_alt.png
  src/pages/Login.jsx
  src/pages/SignUp.jsx
Labels: ✨ feat, 🦋 미경, 🪫 도현

#78 [STYLE] Feed Page CSS 수정, [FEAT] 프로필 이미지 미설정시 기본 프로필 이미지 구현
  package.json
  src/assets/image/user_default.png
  src/assets/image/user_default2.png
  src/components/feed/AddFeedForm.jsx
  src/components/feed/Comments.jsx
  src/components/feed/EditFeedForm.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedList.jsx
  src/components/feed/Like.jsx
  src/constant/BANNED_WORDS.js
  yarn.lock
Labels: ✨ feat, 🧹chore, 🎨 style, 😺영진

#79 fix: 로그인은 되지만 알럿창이 반대로뜨는 오류 수정 #24
  src/pages/SignUp.jsx
Labels: 🐞fix, 🦋 미경, 🪫 도현

#80 bugfix: swal 빠진 부분 수정 / feat: Detail, Comments 유저 기본 프로필 이미지 설정
  src/components/feed/Comments.jsx
  src/components/feed/Like.jsx
  src/pages/Detail.jsx
Labels: ✨ feat, 🎨 style, 🐻 민경

#87 [FEAT] 프로필 이미지 추가 기능
  src/components/feed/FeedCard.jsx
  src/constant/constants.js
Labels: ✨ feat, 📦add, 😺영진

#88 [CHORE] SUPABASE_STORAGE_URL 출처 변경
  src/components/feed/FeedCard.jsx
  src/constant/constants.js
Labels: 🧹chore, 😺영진

#89 chore: 로그인, 회원가입 스타일 수정, 리드미 파일 수정
  README.md
  src/components/user/UserSNSLink.jsx
  src/pages/Login.jsx
  src/pages/SignUp.jsx
Labels: 🧹chore, 🦋 미경

#90 [style] mypage의 피드UI -> FeedCard UI적용 // Card클릭하면 detail페이지로 이동 #48
  src/pages/Mypage.jsx
Labels: 🎨 style, 🐈‍⬛애리

#93 [FEAT] 디테일 페이지 업로드 된 프로필 이미지 보여주는 기능 추가 #92
  src/pages/Detail.jsx
Labels: ✨ feat, 😺영진

#95 [FEAT] detail 페이지 comments에 프로필 이미지 출력
  src/components/feed/Comments.jsx
Labels: ✨ feat, 😺영진

#99 bugfix: Detail페이지에서 삭제시 Swal 적용
  src/pages/Detail.jsx
Labels: 🐞fix, 🐻 민경

#101 feat: 사용자 닉네임을 헤더에 표시하도록 수정
  src/layout/Header.jsx
Labels: ✨ feat, 🐥 수민

#105 [feat] mypage 의 input창 disabled 여부 추가
  src/components/common/Input.jsx
  src/components/user/UserInfo.jsx
Labels: 🔨 refactor, 🐈‍⬛애리

#106 feat: 사용자 닉네임 관리 기능 추가 및 프로필 업데이트 시 반영
  src/components/user/UserInfo.jsx
  src/contexts/AuthContext.jsx
  src/layout/Header.jsx
Labels: 🐞fix, ✨ feat, 🐥 수민

#109 [refactor]Mypage alert추가
  src/components/user/UserInfo.jsx
Labels: 🔨 refactor, 🐈‍⬛애리

#110 프리티어 설정 적용
  .github/ISSUE_TEMPLATE/기능-구현-템플릿.md
  .github/ISSUE_TEMPLATE/버그-발생-템플릿.md
  index.html
  package.json
  src/api/fetchData.js
  src/api/insertOrUpdateData.js
  src/common/Alert.js
  src/components/common/NavigationButton.jsx
  src/components/feed/AddFeedForm.jsx
  src/components/feed/Comments.jsx
  src/components/feed/EditFeedForm.jsx
  src/components/feed/FeedAddButton.jsx
  src/components/feed/FeedCard.jsx
  src/components/feed/FeedList.jsx
  src/components/feed/Like.jsx
  src/components/feed/Modal.jsx
  src/components/user/UserInfo.jsx
  src/components/user/UserProfileImage.jsx
  src/constant/BANNED_WORDS.js
  src/contexts/AuthContext.jsx
  src/contexts/FeedContext.jsx
  src/layout/Header.jsx
  src/layout/StickyMenu.jsx
  src/main.jsx
  src/pages/Detail.jsx
  src/pages/Error.jsx
  src/pages/Login.jsx
  src/pages/Mypage.jsx
  src/pages/SignUp.jsx
  src/supabase/client.js
Labels: 🔨 refactor, 🐥 수민
